apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: argocd-operator
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    control-plane: argocd-operator
